### ISSUE TITLE
ModuleNotFoundError: No module named 'shaarpy'

### ISSUE THREAD

**Issue by Strubbl** [aurelg/shaarpy#1]
I tried installing the module, but it gives the ModuleNotFoundError. Is this a bug or am i doing something wrong?

```
# pip install git+https://github.com/aurelg/shaarpy.git
Collecting git+https://github.com/aurelg/shaarpy.git
  Cloning https://github.com/aurelg/shaarpy.git to /tmp/pip-cw7jb7e2-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-cw7jb7e2-build/setup.py", line 6, in <module>
        from shaarpy import __version__
    ModuleNotFoundError: No module named 'shaarpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-cw7jb7e2-build/

```

**Comment by Strubbl** [comment]
I am getting the same error when i try to install it manually:

```
root@c8dbde07487f:~# git clone https://github.com/aurelg/shaarpy.git
root@c8dbde07487f:~# cd /shaarpy/
root@c8dbde07487f:/shaarpy# python ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 6, in <module>
    from shaarpy import __version__
ModuleNotFoundError: No module named 'shaarpy'
```
